<?php

namespace AW\WorxShareBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersProjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersProjectsRepository extends EntityRepository
{
}
