<?php

namespace AW\WorxShareBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersClientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersClientsRepository extends EntityRepository
{
}
