jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CM:       ROLE_USER
        ROLE_CLIENT:       ROLE_USER
        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                failure_path: /worxshare/login
                login_path: /worxshare/login
                check_path: /worxshare/login_check
                always_use_default_target_path: true
                default_target_path: /worxshare
#                target_path_parameter:  _target_path
                use_referer: false
            logout:       #true
                target: /worxshare
                path: fos_user_security_logout
            anonymous:    true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern: ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            anonymous: ~
#            http_basic:
#                realm: "Secured Demo Area"

    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/worxshare/projects, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/worxshare/clients, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/worxshare/comments, role: IS_AUTHENTICATED_FULLY }
