<?php

namespace AW\TestPlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestsRepository extends EntityRepository
{
}
