<?php

namespace Application\TestCrudBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Test3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Test3Repository extends EntityRepository
{
}
