<?php

namespace Application\LDAPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LDAPMailAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LDAPMailAccountRepository extends EntityRepository
{
}
