<?php

namespace Application\HelpDeskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleCategoryRepository extends EntityRepository
{
	public function findAllOrderByPath(){
		
		return $this->findBy(array(), array('path' => 'ASC'));

	}
}
