<?php

namespace Application\HelpDeskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeviceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceTypeRepository extends EntityRepository
{
}
