<?php

namespace Application\HelpDeskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatusTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusTypeRepository extends EntityRepository
{
}
