<?php

namespace Application\HelpDeskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketIssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketIssueRepository extends EntityRepository
{
}
