<?php

namespace AW\HtmlCheckerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScreenShotsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScreenShotsRepository extends EntityRepository
{
}
